In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [2]:
events = pd.read_csv('./out.csv', low_memory=False)
events.head()

/Users/akukettunen/Desktop/ml-course/sample-project/env/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3155: DtypeWarning: Columns (31,35) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,tulos,vapaataival,vapaa,vaara,koordinaatitX,koordinaatitY,jokerHat,lyoja,lyojaVieras,vvo,...,endtime,lyonti,karkaaminen,tyyppi,lyoty,expiry,pesat0,pesat1,pesat2,pesat3
0,Vapaa,False,NaN,False,NaN,NaN,False,Topi Korhonen,1,False,...,3843.149438,1,False,NaN,True,NaN,Topi Korhonen,Antti Korhonen,Joni Rytkönen,NaN
1,Vapaa,False,NaN,False,NaN,NaN,False,Ossi Meriläinen,1,False,...,10104.901373,3,False,NaN,True,NaN,Ossi Meriläinen,Marko Pelkonen,Jonne Luhtavaara,Onni Määttä
2,Vapaa,False,NaN,False,NaN,NaN,False,Heikki Savikoski,1,False,...,5146.507994,1,False,NaN,True,NaN,Heikki Savikoski,Aki Hanhela,NaN,Marko Pelkonen
3,Palo,False,NaN,False,NaN,NaN,False,Lauri Rönkkö,1,False,...,3960.854124,3,False,NaN,True,NaN,Lauri Rönkkö,Roope Korhonen,Topi Korhonen,Antti Korhonen
4,Kärkilyönti,False,NaN,False,NaN,NaN,False,Lauri Rönkkö,1,False,...,5852.765227,2,False,NaN,True,NaN,Lauri Rönkkö,NaN,Roope Korhonen,Topi Korhonen